apiVersion: apps/v1
kind: Deployment
metadata:
  # name of the deployment
  name: node-deployment 
spec:
  selector:
    matchLabels:
      # looks for this label to make k8 service
      app: node 
  replicas: 3 # 3 pods
  template:
    metadata:
      labels:
        # this label connects to the service/any other k8 components (name of pods)
        app: node 
    spec: # defining container specs
      containers:
      # name of container we'll give it
      - name: node 
        # name of image we're using to make containers in pods
        image: joeburnsjb2/tech254-2tier-app-container:latest 
        ports:
        # what port will we open for our container?
        - containerPort: 3000 
